version: '3.8'

services:
  backend:
    build: 
      context: ./marketplace_project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./marketplace_project:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=your-development-secret-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DATABASE_URL=sqlite:///db.sqlite3
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./marketplace-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./marketplace-frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    command: npm start 