services:
  # Backend Django API Service
  - type: web
    name: marketplace-backend
    env: python
    rootDir: marketplace_project
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://marketplace-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString
    healthCheckPath: /api/health/
    autoDeploy: true

  # Frontend React Service
  - type: static
    name: marketplace-frontend
    rootDir: marketplace-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://marketplace-backend.onrender.com/api
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: marketplace-db
    databaseName: marketplace
    user: marketplace
    plan: free 