services:
  # Backend API service
  - type: web
    name: marketplace-backend
    env: python
    region: oregon
    buildCommand: cd marketplace_project && pip install -r requirements.txt
    startCommand: cd marketplace_project && gunicorn backend.wsgi:application --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://marketplace-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: marketplace-db
          property: connectionString
    healthCheckPath: /api/health/
    autoDeploy: true

  # Frontend static site
  - type: web
    name: marketplace-frontend
    env: static
    buildCommand: cd marketplace-frontend && npm install && npm run build
    staticPublishPath: ./marketplace-frontend/build
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: REACT_APP_API_URL
        value: https://marketplace-backend.onrender.com/api
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: marketplace-db
    region: oregon
    plan: free 